li@DESKTOP-8MFH59G MINGW64 /e/Git (master) $ git pus -h git: 'pus' is not a git command. See 'git --help'.
The most similar commands are
        push
        pull

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git push -h
usage: git push [<options>] [<repository> [<refspec>...]]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --repo <repository>   repository
    --all                 push all refs
    --mirror              mirror all refs
    -d, --delete          delete refs
    --tags                push tags (can't be used with --all or --mirror)
    -n, --dry-run         dry run
    --porcelain           machine-readable output
    -f, --force           force updates
    --force-with-lease[=<refname>:<expect>]
                          require old value of ref to be at this value
    --recurse-submodules (check|on-demand|no)
                          control recursive pushing of submodules
    --thin                use thin pack
    --receive-pack <receive-pack>
                          receive pack program
    --exec <receive-pack>
                          receive pack program
    -u, --set-upstream    set upstream for git pull/status
    --progress            force progress reporting
    --prune               prune locally removed refs
    --no-verify           bypass pre-push hook
    --follow-tags         push missing but relevant tags
    --signed[=(yes|no|if-asked)]
                          GPG sign the push
    --atomic              request atomic transaction on remote side
    -o, --push-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git push origin1 master master
error: dst ref refs/heads/master receives from more than one src
error: failed to push some refs to 'https://github.com/lihong2020/Git.git'

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git push -f origin1 master master
error: dst ref refs/heads/master receives from more than one src
error: failed to push some refs to 'https://github.com/lihong2020/Git.git'

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git push origin1 master: refs/for/master
fatal: invalid refspec 'master:'

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git push origin1 master :refs/for/master
remote: warning: Deleting a non-existent ref.
To https://github.com/lihong2020/Git.git
 - [deleted]         refs/for/master

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git reflog
976f1de (HEAD -> master, origin1/master) HEAD@{0}: reset: moving to 976f
8ba2eb7 HEAD@{1}: commit: delete readme.txt
976f1de (HEAD -> master, origin1/master) HEAD@{2}: reset: moving to 976f
976f1de (HEAD -> master, origin1/master) HEAD@{3}: commit: 新建了一个文件夹和修改了license.txt
284335a HEAD@{4}: reset: moving to 284335a
54f6553 HEAD@{5}: reset: moving to 54f6
294e207 HEAD@{6}: reset: moving to 294e207
294e207 HEAD@{7}: reset: moving to HEAD^
284335a HEAD@{8}: pull: Fast-forward
294e207 HEAD@{9}: commit: 2020/12/13
60fd647 HEAD@{10}: commit: test add a ifo
54f6553 HEAD@{11}: pull: Fast-forward
fe2283e HEAD@{12}: reset: moving to HEAD^
e1683a6 HEAD@{13}: commit: 2020/11/4 delete a file
fe2283e HEAD@{14}: commit: add a line
c99f085 HEAD@{15}: reset: moving to c99f08
7be479a HEAD@{16}: commit: Delete a file
c99f085 HEAD@{17}: reset: moving to c99f085
c99f085 HEAD@{18}: commit: ThirdTime
69795d6 HEAD@{19}: reset: moving to 69795
1a153d5 HEAD@{20}: reset: moving to HEAD^
69795d6 HEAD@{21}: commit: append GPL
1a153d5 HEAD@{22}: commit (initial): Wrote a readme file

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git rename -h
git: 'rename' is not a git command. See 'git --help'.

The most similar command is
        rebase

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git remote rename -h
usage: git remote rename <old> <new>

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git remote rename Git Git_Lhs
fatal: No such remote: 'Git'

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git remote rename origin1 Git_Lhs

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git remote -v
Git_Lhs https://github.com/lihong2020/Git.git (fetch)
Git_Lhs https://github.com/lihong2020/Git.git (push)

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git remote rename Git_Lhs origin

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git remote
origin

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ ^C

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git check -h
git: 'check' is not a git command. See 'git --help'.

The most similar command is
        checkout

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git checkout -h
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

    -b <branch>           create and checkout a new branch
    -B <branch>           create/reset and checkout a branch
    -l                    create reflog for new branch
    --guess               second guess 'git checkout <no-such-branch>' (default)
    --overlay             use overlay mode (default)
    -q, --quiet           suppress progress reporting
    --recurse-submodules[=<checkout>]
                          control recursive updating of submodules
    --progress            force progress reporting
    -m, --merge           perform a 3-way merge with the new branch
    --conflict <style>    conflict style (merge or diff3)
    -d, --detach          detach HEAD at named commit
    -t, --track           set upstream info for new branch
    -f, --force           force checkout (throw away local modifications)
    --orphan <new-branch>
                          new unparented branch
    --overwrite-ignore    update ignored files (default)
    --ignore-other-worktrees
                          do not check if another worktree is holding the given ref
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character

li@DESKTOP-8MFH59G MINGW64 /e/Git (master)
$ git checkout -b dev
Switched to a new branch 'dev'

li@DESKTOP-8MFH59G MINGW64 /e/Git (dev)
$ vim license.txt

li@DESKTOP-8MFH59G MINGW64 /e/Git (dev)
$ cat license.txt
我叫李宏松
上传一个测试信息。

2020/12/13再试一次
--来自网页端的改动
编辑一些内容vim工具
/**在dev分支上面修改了license.txt**/

li@DESKTOP-8MFH59G MINGW64 /e/Git (dev)
$ git add --all

li@DESKTOP-8MFH59G MINGW64 /e/Git (dev)
$ git commit -m